// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh_a8nO1L4NZ0p-_9tnwkzPVC1quDjl1U',
    appId: '1:663607029153:web:c451d376100041406aafe0',
    messagingSenderId: '663607029153',
    projectId: 'crud-firebase-9b875',
    authDomain: 'crud-firebase-9b875.firebaseapp.com',
    storageBucket: 'crud-firebase-9b875.appspot.com',
    measurementId: 'G-QVRKTVQZMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5PTm44N_YjX1lP2PGSvHtJQc6AF_bDIE',
    appId: '1:663607029153:android:604babdb4717098a6aafe0',
    messagingSenderId: '663607029153',
    projectId: 'crud-firebase-9b875',
    storageBucket: 'crud-firebase-9b875.appspot.com',
  );
}
